//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCInventoryManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<int> Shipper_ID { get; set; }
        public Nullable<int> PaymentInfo_ID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual PaymentInfo PaymentInfo { get; set; }
        public virtual Shipper Shipper { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
